# Generated by Skyramp v1.3.29 on 2026-06-25 21:39:19.433714857 +0000 UTC m=+330.043435602
# Command: skyramp generate contract rest http://localhost/api/v2/weightentry/summary/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_weightentry_summary_auth.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/weightentry/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 401
    assert skyramp.get_response_value(summary_GET_response, "detail") is not None


if __name__ == "__main__":
    test_summary_get()
