# Generated by Skyramp v1.3.40 on 2026-08-27 21:29:51.697917 -0700 PDT m=+829.199020417
# Command: skyramp generate contract rest http://localhost:8000/api/v2/weightentry/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_weightentry_year_out_of_range.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--provider-output contract_weightentry_year_out_of_range.py \
# 		--query-params year=-2024 \
# 		--response-status-code 400 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v2/weightentry/ GET
def test_weightentry_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    weightentry_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": "-2024"}
    )

    # Generated Assertions
    assert weightentry_GET_response.status_code == 400
    assert skyramp.get_response_value(weightentry_GET_response, "year.0") == "Enter a number."
    assert skyramp.get_response_value(weightentry_GET_response, "year.1") is None


if __name__ == "__main__":
    test_weightentry_get()
