# Generated by Skyramp v1.3.29 on 2026-06-26 23:25:37.416454489 +0000 UTC m=+267.911183155
# Command: skyramp generate contract rest http://localhost/api/v2/measurement/{id}/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output measurement_detail_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/measurement/{id}/ GET
def test_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = 99999

    # Expected Response Body
    expected_id_GET_response_body = r'''{
        "detail": "Not found."
    }'''

    # Execute Request
    id_GET_response = client.send_request(
        url=URL,
        path="/api/v2/measurement/{id}/",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert id_GET_response.status_code == 404
    assert skyramp.check_schema(id_GET_response, expected_id_GET_response_body)
    assert skyramp.get_response_value(id_GET_response, "detail") is not None


if __name__ == "__main__":
    test_id_get()
