# Generated by Skyramp v1.3.29 on 2026-06-26 23:25:50.243131861 +0000 UTC m=+280.737860526
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_category_name_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_measurement-category-name-verification.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "TestCategory-1782516000",
        "unit": "kg"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestCategory-1782516000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    category_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    endpoint_2_POST_request_body = f'''{{
        "category": "{category_id}",
        "date": "2026-06-26",
        "notes": "test measurement",
        "value": "75.50"
    }}'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "category") == category_id
    assert skyramp.get_response_value(endpoint_2_POST_response, "category_name") == "TestCategory-1782516000"
    assert str(skyramp.get_response_value(endpoint_2_POST_response, "date")).startswith("2026-06-26")
    assert float(skyramp.get_response_value(endpoint_2_POST_response, "value")) == 75.5
    assert skyramp.get_response_value(endpoint_2_POST_response, "notes") == "test measurement"

    measurement_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/{measurement}/",
        method="GET",
        headers=headers,
        path_params={"measurement": measurement_id}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_3_GET_response, "id") == measurement_id
    assert skyramp.get_response_value(endpoint_3_GET_response, "category") == category_id
    assert skyramp.get_response_value(endpoint_3_GET_response, "category_name") == "TestCategory-1782516000"
    assert str(skyramp.get_response_value(endpoint_3_GET_response, "date")).startswith("2026-06-26")
    assert float(skyramp.get_response_value(endpoint_3_GET_response, "value")) == 75.5
    assert skyramp.get_response_value(endpoint_3_GET_response, "notes") == "test measurement"


if __name__ == "__main__":
    test_integration()
