# Generated by Skyramp v1.3.29 on 2026-06-26 23:25:17.18784385 +0000 UTC m=+247.682572495
# Command: skyramp generate contract rest http://localhost/api/v2/measurement/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output measurement_get_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/measurement/ GET
def test_measurement_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_measurement_GET_response_body = r'''{
        "count": 1,
        "results": [
            {
                "id": "019f0644-91bf-7748-8a13-17696c393be5",
                "category": "019f0644-91a1-74f1-aad9-27a6f7a62c62",
                "category_name": "TestCategory-1782516000",
                "date": "2026-06-26T00:00:00+02:00",
                "value": 75.5,
                "notes": "test measurement"
            }
        ]
    }'''

    # Execute Request
    measurement_GET_response = client.send_request(
        url=URL,
        path="/api/v2/measurement/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert measurement_GET_response.status_code == 200
    assert skyramp.check_schema(measurement_GET_response, expected_measurement_GET_response_body)
    assert skyramp.get_response_value(measurement_GET_response, "count") is not None
    assert skyramp.get_response_value(measurement_GET_response, "count") >= 0
    assert skyramp.get_response_value(measurement_GET_response, "results.0.category_name") is not None


if __name__ == "__main__":
    test_measurement_get()
