# Generated by Skyramp v1.3.29 on 2026-06-25 20:38:26.682450282 +0000 UTC m=+247.547346791
# Command: skyramp generate contract rest http://localhost/api/v2/weightentry/summary/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output weightentry_summary_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/weightentry/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_summary_GET_response_body = r'''{
        "count": 0,
        "min_weight": "70.000",
        "max_weight": "80.000",
        "avg_weight": "75.000"
    }'''

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.check_schema(summary_GET_response, expected_summary_GET_response_body)
    assert skyramp.get_response_value(summary_GET_response, "count") is not None
    assert skyramp.get_response_value(summary_GET_response, "count") >= 0
    assert "min_weight" in summary_GET_response.json()
    assert "max_weight" in summary_GET_response.json()
    assert "avg_weight" in summary_GET_response.json()


if __name__ == "__main__":
    test_summary_get()
