# Generated by Skyramp v1.3.29 on 2026-06-25 19:43:10.127850913 +0000 UTC m=+617.063188439
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_year_filter_isolation_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_weightentry-year-filter-isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-06-15",
        "weight": "75.00"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") == "2024-06-15"
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "75.00"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": ["2024"]}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") >= 1
    results = skyramp.get_response_value(endpoint_1_GET_response, "results")
    assert results is not None
    assert len(results) >= 1
    created_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    matching = [r for r in results if r.get("id") == created_id]
    assert len(matching) == 1
    assert matching[0]["date"].startswith("2024-")
    assert matching[0]["weight"] == "75.00"
    for entry in results:
        assert entry["date"].startswith("2024-"), f"Expected 2024 date, got {entry['date']}"


if __name__ == "__main__":
    test_integration()
