# Generated by Skyramp v1.3.29 on 2026-06-25 20:46:43.500766932 +0000 UTC m=+740.414627769
# Command: skyramp generate contract rest http://localhost/api/v2/weightentry/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output weightentry_no_year_filter_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/weightentry/ GET
def test_weightentry_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_weightentry_GET_response_body = r'''{
        "count": 123,
        "results": [
            {
                "date": "2024-06-15T00:00:00Z",
                "id": 1,
                "user": 1,
                "weight": "80.00"
            }
        ]
    }'''

    # Execute Request
    weightentry_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert weightentry_GET_response.status_code == 200
    assert skyramp.check_schema(weightentry_GET_response, expected_weightentry_GET_response_body)
    assert skyramp.get_response_value(weightentry_GET_response, "count") is not None
    count = skyramp.get_response_value(weightentry_GET_response, "count")
    assert count >= 0
    if count > 0:
        assert skyramp.get_response_value(weightentry_GET_response, "results.0.id") > 0
        assert skyramp.get_response_value(weightentry_GET_response, "results.0.weight") is not None
        assert skyramp.get_response_value(weightentry_GET_response, "results.0.date") is not None


if __name__ == "__main__":
    test_weightentry_get()
