# Generated by Skyramp v1.3.29 on 2026-06-25 20:44:49.699202936 +0000 UTC m=+626.613063783
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_year_filter_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_weightentry-year-filter.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-06-15",
        "weight": "80.00"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "80.00"
    assert "2024" in str(skyramp.get_response_value(endpoint_1_POST_response, "date"))
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "user") is not None

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2023-06-15",
        "weight": "75.00"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "75.00"
    assert "2023" in str(skyramp.get_response_value(endpoint_1_POST_1_response, "date"))
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "user") is not None

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": ["2024"]}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") is not None
    entry_1_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    entry_2_id = skyramp.get_response_value(endpoint_1_POST_1_response, "id")
    result_count = skyramp.get_response_value(endpoint_1_GET_response, "count")
    result_ids = [skyramp.get_response_value(endpoint_1_GET_response, f"results.{i}.id") for i in range(min(result_count, 20))]
    assert entry_1_id in result_ids
    assert entry_2_id not in result_ids
    for i in range(min(result_count, 20)):
        assert "2024" in str(skyramp.get_response_value(endpoint_1_GET_response, f"results.{i}.date"))


if __name__ == "__main__":
    test_integration()
