# Generated by Skyramp v1.3.29 on 2026-06-25 19:41:35.573193123 +0000 UTC m=+512.059385202
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_summary_aggregate_verification_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_weightentry-summary-aggregate-verification.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    token = (os.getenv("SKYRAMP_TEST_TOKEN") or "").strip()
    if token:
        headers["Authorization"] = "Token " + token

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2026-01-15",
        "weight": "75.50"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "75.50"
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") == "2026-01-15"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2026-01-16",
        "weight": "85.50"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "85.50"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "date") == "2026-01-16"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") >= 2
    assert skyramp.get_response_value(endpoint_2_GET_response, "min_weight") is not None
    assert skyramp.get_response_value(endpoint_2_GET_response, "max_weight") is not None
    assert skyramp.get_response_value(endpoint_2_GET_response, "avg_weight") is not None


if __name__ == "__main__":
    test_integration()
