# Generated by Skyramp v1.3.29 on 2026-06-25 20:38:55.157687677 +0000 UTC m=+276.022584196
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_summary_aggregate_calc_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_weightentry-summary-aggregate-calc.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-01-15",
        "weight": "70.000"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") == "2024-01-15"
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "70.000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2024-01-16",
        "weight": "80.000"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "date") == "2024-01-16"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "80.000"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") is not None
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") >= 0
    assert "min_weight" in endpoint_2_GET_response.json()
    assert "max_weight" in endpoint_2_GET_response.json()
    assert "avg_weight" in endpoint_2_GET_response.json()


if __name__ == "__main__":
    test_integration()
