# Generated by Skyramp v1.3.29 on 2026-06-25 19:41:27.095486015 +0000 UTC m=+503.581678083
# Command: skyramp generate contract rest http://localhost/api/v2/weightentry/summary/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output weightentry_summary_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/weightentry/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    token = (os.getenv("SKYRAMP_TEST_TOKEN") or "").strip()
    if token:
        headers["Authorization"] = "Token " + token

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.get_response_value(summary_GET_response, "count") >= 0
    assert skyramp.get_response_value(summary_GET_response, "count") is not None


if __name__ == "__main__":
    test_summary_get()
