# Generated by Skyramp v1.3.40 on 2026-08-27 21:30:25.17655 -0700 PDT m=+862.677629584
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_year_filter_isolates_calendar_year_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger/wger/wger/tests/skyramp/scenario_weightentry_year_filter_isolates_calendar_year.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    format = "json"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2014-03-15",
        "weight": "80.50"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "80.50"
    assert str(skyramp.get_response_value(endpoint_1_POST_response, "date")).startswith("2014-03-15")
    assert int(skyramp.get_response_value(endpoint_1_POST_response, "id")) > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "user") is not None

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2015-03-15",
        "weight": "81.50"
    }'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "81.50"
    assert str(skyramp.get_response_value(endpoint_1_POST_1_response, "date")).startswith("2015-03-15")
    assert int(skyramp.get_response_value(endpoint_1_POST_1_response, "id")) > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={
            "format": [format],
            "year": ["2014"]
        }
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.weight") == "80.50"
    assert str(skyramp.get_response_value(endpoint_1_GET_response, "results.0.date")).startswith("2014-")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None

    # Execute Request
    endpoint_1_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={
            "format": [format],
            "ordering": ["date"]
        }
    )

    # Generated Assertions
    assert endpoint_1_GET_1_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "count") == 2
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "results.1.id") == skyramp.get_response_value(endpoint_1_POST_1_response, "id")
    assert str(skyramp.get_response_value(endpoint_1_GET_1_response, "results.1.date")).startswith("2015-")
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "results.2") is None

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204

    # Execute Request
    endpoint_2_DELETE_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": skyramp.get_response_value(endpoint_1_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_2_DELETE_1_response.status_code == 204


if __name__ == "__main__":
    test_integration()
