# Generated by Django 6.0.8 on 2026-08-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0003_migrate_context_data_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='trophy_type',
            field=models.CharField(choices=[('time', 'Time-based'), ('volume', 'Volume-based'), ('count', 'Count-based'), ('sequence', 'Sequence-based'), ('streak', 'Streak-based'), ('date', 'Date-based'), ('pr', 'Personal Record'), ('other', 'Other')], default='other', help_text='The type of criteria used to evaluate this trophy', max_length=20, verbose_name='Trophy type'),
        ),
    ]
